
version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: 'kafka'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_NUM_PARTITIONS=2
      - KAFKA_CONFLUENT_TOPIC_REPLICATION_FACTOR=1

    depends_on:
      - zookeeper

  kafka-2:
    image: 'bitnami/kafka:latest'
    container_name: 'kafka-2'
    ports:
      - '9094:9094'
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_LISTENERS=PLAINTEXT://:9094
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9094
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_NUM_PARTITIONS=2
      - KAFKA_CONFLUENT_TOPIC_REPLICATION_FACTOR=1
      
    depends_on:
      - zookeeper

  kafka-3:
    image: 'bitnami/kafka:latest'
    container_name: 'kafka-3'
    ports:
      - '9095:9095'
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_LISTENERS=PLAINTEXT://:9095
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9095
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_NUM_PARTITIONS=2
      - KAFKA_CONFLUENT_TOPIC_REPLICATION_FACTOR=1

    depends_on:
      - zookeeper
